url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Jekyll Bootstrap Starter" # the name of your site, e.g. ACME Corp.
tagline: "An awesome tagline"
email: "your.email@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
author: KPMG

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap